import { defineCollection, defineContentConfig, property, z, } from '@nuxt/content';

const hideAutoGeneratedFields = {
  seo: property(z.object({})).editor({ hidden: true }),
  navigation: property(z.object({})).editor({ hidden: true }),
  excerpt: property(z.object({})).editor({ hidden: true }),
  title: property(z.string()).editor({ hidden: true }),
  description: property(z.string()).editor({ hidden: true }),
};

export default defineContentConfig({
  collections: {
    activities: defineCollection({
      type: 'page',
      source: 'activities/*.md',
      schema: z.object({
        ...hideAutoGeneratedFields,
        image: property(z.string()).editor({ input: 'media' }),
        title: z.string(),
        date: z.date(),
        price: z
          .number()
          .refine((v) => Number.isFinite(v), 'price must be a valid number'),
        tag: z.string().optional(),
      }),
    }),
    news: defineCollection({
      type: 'page',
      source: 'news/*.md',
      schema: z.object({
        ...hideAutoGeneratedFields,
        image: property(z.string()).editor({ input: 'media' }),
        title: z.string(),
        date: z.date(),
        teaser: z.string().optional(),
      }),
    }),
    pages: defineCollection({
      type: 'page',
      source: 'pages/*.md',
      schema: z.object(hideAutoGeneratedFields),
    }),
    info_: defineCollection({
      type: 'page',
      source: 'info/*.md',
      schema: z.object(hideAutoGeneratedFields),
    }),
    stories: defineCollection({
      type: 'page',
      source: 'stories/*.md',
      schema: z.object({
        ...hideAutoGeneratedFields,
        image: property(z.string()).editor({ input: 'media' }),
        title: z.string(),
        date: z.date(),
        author: z.string(),
        teaser: z.string().optional(),
      }),
    }),
    shared: defineCollection({
      type: 'data',
      source: 'shared/*.md',
      schema: z.object({}),
    }),
  },
});
